# Python Basic
- 본 실습에서는 
    - Jupyter Notebook 을 이용하는 방법과 
    - Markdown 설정 방법,
    - 파이썬을 활용한 기본적인 연산과 자료형에 대해 알아보고자 합니다. 

## 1. Language Basics

#a bove

#m : 마크다운으로 변환

type: int, float, str, bool, ...

In [1]:
# 변수를 정의
x=10
y=3

In [ ]:
#b elow

### (1) Operators
- 간단한 사칙연산과 그 결과를 확인해봅시다.

#### 사칙연산자
- = : 대입
- \+ : 더하기
- \- : 빼기
- \* : 곱하기
- / : 나누기
- // : 나누기 (몫)
- % : 나눈 후 나머지 (mod)
- ** : 제곱

#### 관계연산자
- == : equal to
- != : not equal to
- \> : is bigger than 
- \< : is smaller than 
- \>= : is bigger than or equal to
- \<= : is smaller than or equal to

#### 이항연산자 (Boolean Operators)
- not
- and
- or

In [8]:
x+y

13

In [5]:
x**y

1000

In [6]:
x/y

3.3333333333333335

In [7]:
x/float(y)

3.3333333333333335

- 정수를 문자로 취급할 경우를 확인해봅시다.

In [ ]:
str(x) + "+" + str(y)

### (2) None
- 값이 존재하지 않는 변수에 None 을 부여하고 함수 정의를 해봅시다.

In [ ]:
# 변수의 값이 None 을 가질 수 있다.
x = None

In [ ]:
# 리스트는 None 을 원소로 가질 수 있다.
array = [1,2, None]

In [ ]:
# 함수는 None을 리턴(Return) 할 수 있다.
def func():
    return None

- Boolean을 이용한 논리연산을 통해 객체가 None에 해당하는 지 확인해봅시다. 

In [ ]:
if [] != [None]:
    print("Not Equal")

### (3) Indents
- 함수를 정의하거나 루프(loop)가 발생할 때 하위 항목에 대해서는 indentation이 필수이며, 다음과 같은 형태를 띄고 있습니다.

In [ ]:
def sign(num) : 
    # 첫번째 레벨 indentation : 함수 body
    if num == 0 : 
        # 두번째 레벨 indentation : if 구문 body
        print("Zero")
    elif num > 0 : 
        # 두번째 레벨 indentation : elif 구문 body
        print("Positive")
    else: 
        # 두번째 레벨 indentation : else 구문 body
        print("Negative")

### (4) List
- 리스트를 정의하고 각 요소의 위치와 타입을 확인하고, 원소를 추가해보도록 하겠습니다.

In [ ]:
# 리스트를 정의하여 names라는 변수로 저장한다.
names = ['Zach', 'Jay']

In [ ]:
# 첫 번째 원소가 Zach인지 확인한다.
names[0] == 'Zach'

In [ ]:
# Richard 원소를 추가한다.
names.append('Richard')

In [ ]:
# 리스트의 길이와 현재 리스트를 확인해본다.
print(len(names) == 3)
print(names)

In [ ]:
# 또 다른 리스트의 원소들을 기존 리스트에 추가한다. 
names += ['Abi','Kevin']
print(names)

- 빈 리스트를 생성하는 법을 알아봅시다.

In [ ]:
names = []
print(names)

In [ ]:
names = list()
print(names)

- 리스트는 여러가지 타입의 원소를 포함할 수 있습니다. 

In [ ]:
stuff = [1, ['hi','bye'], -0.12, None]

In [ ]:
stuff

- 원소의 인덱스를 이용하여 리스트 일부 원소를 확인해봅시다. 

In [ ]:
# 리스트를 numbers라는 변수에 저장한다.
numbers = [0,1,2,3,4,5,6]

In [ ]:
# 0~2 번째 원소를 확인한다.
print(numbers[0:3])
print(numbers[:3])
print([0,1,2])

In [ ]:
# 5번째 이후의 원소를 확인한다.
print(numbers[5:])
print(numbers[5:7])
print([5,6])

In [ ]:
# 전체 원소를 확인한다.
print(numbers[:])
print(numbers)
print([0,1,2,3,4,5,6])

- 리스트 슬라이싱을 음수로 적용해봅시다.

In [ ]:
numbers[-1]

마지막 index : -1

In [ ]:
numbers[-3:]

In [ ]:
numbers[3:-2]

### (5) Tuples
- 튜플을 정의하고 활용해봅시다.

In [ ]:
# 튜플을 names라는 변수에 저장한다.
names = ('Zach','Jay')

In [ ]:
# 0번째 원소를 확인한다.
names[0]

In [ ]:
# 튜플의 길이와 현재 튜플을 확인해본다.
print(len(names) == 2)
print(names)

In [ ]:
# 튜플의 특정 인덱스에 원소를 assign 하는 것이 불가하다.
names[0] = 'Richard'

- 빈 튜플을 생성하는 법을 알아봅시다.

In [ ]:
empty = tuple()
print(empty)

In [ ]:
single = (10,)
print(single)

### (6) Dictionary
- 딕셔너리를 정의하고 원소를 추가 및 삭제해봅시다. 

- 빈 딕셔너리는 다음 두 가지 방법으로 정의할 수 있습니다.

In [9]:
# 딕셔너리를 phonebook 변수에 저장한다.
phonebook = {}

In [10]:
# 딕셔너리를 phonebook 변수에 저장한다.
phonebook = dict()

- 다음으로, 빈 딕셔너리에 두 가지 방법을 이용하여 원소를 추가해봅시다.

In [11]:
phonebook = {'Zach':'12-37'}
phonebook['Jay'] = '34-23'

In [12]:
# 원소가 딕셔너리에 존재하는 지 확인해본다.
print('Zach' in phonebook)
print('Kevin' in phonebook) 
print(phonebook['Jay'])

True
False
34-23


- 원소를 삭제해봅시다.

In [13]:
del phonebook['Zach']
print(phonebook)

{'Jay': '34-23'}


### (7) Loops
- 루프(loops)를 사용하여 반복문을 작성해봅시다.

#### for-loop
```python
for 범위지정:
    반복문내용
```
- for i <- 1 to 10
    - for i in [1,2,3,4,5,6,7,8,9,10]:
- python은 0 부터 사용하도록 한다
    - for i in [0,1,2,3,4,5,6,7,8,9]
- range()를 사용
    - range(10) = [0,1,2,3,4,5,6,7,8,9]

In [ ]:
for i in range(10):
    print(i)

- 리스트에 반복문을 적용해봅시다.

In [ ]:
# 리스트를 names라는 변수에 저장한다.
names = ['Zach','Jay','Richard']

In [ ]:
# 리스트 내 모든 원소 앞에 hi 를 붙여 출력한다.

for name in names:
    print('Hi'+name+'!')

In [ ]:
# 인덱스와 값을 함께 출력한다.
for i in range(len(names)):
    print(i, names[i])

In [ ]:
# enumerate 함수를 이용하여 인덱스와 값을 함께 출력할 수 있다.
for i, name in enumerate(names):
    print(i, name)

- 딕셔너리에 반복문을 적용해봅시다.

In [ ]:
# 딕셔너리를 phonebook 라는 변수에 저장한다.
phonebook = {'Zach':'12-37', 'Jay':'34-23'}

In [ ]:
# 딕셔너리의 key를 모두 출력한다.
for name in phonebook:
    print(name)

In [ ]:
# 딕셔너리의 value를 모두 출력한다.
for number in phonebook.values():
    print(number)

In [ ]:
# 딕셔너리의 모든 item을 출력한다.
for name, number in	phonebook.items():
    print(name, number)

#### while-loop
```python
while 조건 :
    반복문내용
```
- for 와  while 의 loop 문에서는 break 과 continue 의 키워드를 사용할 수 있습니다.

In [ ]:
i = 0
while True :
    print(i)
    i = i + 1
    if i >= 5 :
        break

### (8) Functions and Classes

#### 함수 
- 함수 정의(function definition) : 
```python
def function_name(argument1, argument2, ...):
    line1
    line2
    ...
    return result
```
    - 인자(argument)/매개변수(parameter) : 사용자 혹은 다른 코드로부터 받아 함수 안에서 사용하고 싶은 변수
    - 함수의 내용을 작성할 때 들여쓰기를 하도록 한다.
    - 함수의 output이 있을 경우, return 키워드를 이용하여 내뱉도록 한다.
    - 함수에서 따로 output 을 낼 필요가 없는 경우, return 은 생략 가능하다.
    
   


In [ ]:
def my_function(arg1,arg2):
    # I will add two arguments
    result = arg1 + arg2
    return result

#### 디폴트 인수(default value)
- 함수 매개변수에 기본값을 부여할 수 있다.
- 디폴드 인수가 있을 경우, 함수를 사용할 때, 인수가 생략되면 해당 값을 사용한다.
- Remark:
    - 디폴트 인수는 함수의 인자들 중 마지막 인자들부터 설정해 줄 수 있다.

In [ ]:
def add(n1,n2=0):
    return n1+n2

#### Class 
- class(클래스)와 instance(인스턴스)
- class의 정의 및 구성 : 
```python
class Class_name:
    
    var1 = ...                   # class variable shared by all instances
    var2 = ... 
    
    def __init__(self, arg1, arg2, ...):
        self.member1 = arg1      # instance variable unique to each instance
        self.member2 = arg2
        ...
    
    def function_1(self, a, b ...):   # class methods
        line1_1
        line1_2
        ...
        
    def function_2(self, a, b...):
        line2_1
        line2_2
        self.function_1(a, b)
        ...        
```
- class는 다음의 두가지 종류의 attribute(속성)를 갖는다 : data attribute, methods
    - data attribute (member, 멤버 변수) : 각 인스턴스의 특징이나 인스턴스에 속한 데이터들을 나타내기 위한 값
    - methods (member function, 멤버 함수, 메소드) : 해당 클래스와 관련된 동작을 수행하는 함수
- \_\_init__ (생성자) : 객체가 '생성'될 때 자동으로 호출되는 특별한 멤버 함수
    - 각각의 인스턴스와 관련된 멤버 변수를 설정할 수 있다.
- self 
    - class 내부에서, 해당 class 안에 있는 다른 속성들 (멤버 변수/멤버 함수 등)을 호출할 때 self를 사용한다.
    - class의 멤버 함수를 정의할 때, 해당 함수 내에서 해당 클래스의 속성들을 사용할 수 있도록 self를 첫번째 인자로 넣어준다.


- 클래스를 정의하고 함수를 추가해봅시다.

In [ ]:
class Animal(object):
    def __init__(self, species, age):
        self.species = species 
        self.age = age

    def is_person(self): 
        return self.species

    def age_one_year(self): 
        self.age += 1

# Dog 클래스는 Animal 클래스를 계승한다.
class Dog(Animal):
    def age_one_year(self): 
        self.age += 7


### (9) Import Packages
- 파이썬에서는 여러가지 패키지를 설치하고, 사용할 수 있습니다.
- 여러가지 패키지와 모듈을 불러오는 코드를 작성해봅시다.

In [4]:
# os 모듈과 time 모듈을 불러온다.
import os, time

# numpy 패키지를 np라는 이름으로 불러온다.
import numpy as np

# 모듈 내 특정 하위 모듈이나 함수, 또는 패키지를 불러온다.
# 패키지를 불러오는 것 이므로 앞에 모듈명 안붙이고 함수 실행이 가능하다
from numpy import linalg as la, dot as matrix_multiply

## 2. Introduction to NumPy
- 본 노트북 코드에서는 numpy 모듈을 이용하여 배열을 정의하고 활용하는 방법에 대해 알아보고자 합니다.
### (1) np.ndarray Operations

-  다양한 형태의 배열을 x,y,z 에 저장하고 형태를 확인해봅시다.

In [7]:
# 배열을 정의하고 x,y,z 변수에 각각 저장한다.
x = np.array([1,2,3]) # 1차원
y = np.array([[3,4,5]])
z = np.array([[6,7],[8,9]])
print(x,y,z)

[1 2 3] [[3 4 5]] [[6 7]
 [8 9]]


In [6]:
# x,y,z 각각의 형태를 확인한다.
print(x.shape) 
print(y.shape) 
print(z.shape)

(3,)
(1, 3)
(2, 2)


- 특정 조건의 원소를 추출해봅시다.

In [8]:
# 배열을 x라는 변수에 저장한다.
x = np.array([[1,2],[3,4],[5,6]])

In [9]:
print(np.max(x));

6


In [11]:
# 각 행에서 가장 큰 값을 출력한다.
print(np.max(x,axis=1))

# 각 열에서 가장 큰 값을 출력한다.
print(np.max(x, axis=0))

[2 4 6]


In [12]:
# keepdims 매개변수를 활용하여 축을 유지하도록 지정하면 결과 배열의 형상(shape)이 입력 배열과 동일한 형상을 유지할 수 있다.
print(np.max(x, axis=1, keepdims=True))

[[2]
 [4]
 [6]]


### (2) Indexing
- 리스트의 슬라이싱과 유사한 개념으로, 배열의 일부를 추출하기 위해 사용할 수 있는 방법과 그 결과를 확인해봅시다.

In [13]:
import numpy as np

In [16]:
# 랜덤으로 생성한 (3,4) 형태의 배열을 생성하여 변수 x에 저장한다.
x = np.random.random((3,4))
# 배열 전체를 확인한다.
x[:]

array([[0.01411491, 0.26172354, 0.18979596, 0.90032504],
       [0.57706828, 0.04222389, 0.42050077, 0.22179183],
       [0.85677658, 0.32888383, 0.086087  , 0.90585434]])

In [28]:
# 0번째 행과 2번째 행을 선택한다.
x[np.array([0,2]),:]

# x[0:2, :]

array([[0.01411491, 0.26172354, 0.18979596, 0.90032504],
       [0.85677658, 0.32888383, 0.086087  , 0.90585434]])

In [19]:
# 1번째 행의 1~2번째 열을 추출한다.
x[1,1:3]

array([0.04222389, 0.42050077])

In [29]:
# x 의 원소 중 0.5 초과인 값만 추출한다.
x[x>0.5]

array([0.90032504, 0.57706828, 0.85677658, 0.90585434])

In [30]:
# (3,4,1) 형태의 3차원 벡터로 바꿔준다.
x[:,:, np.newaxis]

array([[[0.01411491],
        [0.26172354],
        [0.18979596],
        [0.90032504]],

       [[0.57706828],
        [0.04222389],
        [0.42050077],
        [0.22179183]],

       [[0.85677658],
        [0.32888383],
        [0.086087  ],
        [0.90585434]]])

### (3) Broadcasting
- 일반적으로 numpy에서는 서로 다른 모양의 배열끼리는 연산이 불가합니다. 하지만 어떤 특정 조건이 만족되면 서로 다른 모양의 배열끼리도 연산을 수행할 수 있고, 이를 브로드캐스팅(broadcasting)이라고 합니다.
- 서로 다른 형태의 배열을 정의하고 연산을 수행해봅시다.

In [31]:
# 서로 다른 형태의 배열을 정의하여 x,y,z 각각 변수에 저장합니다.
x = np.random.random((3,4))
y = np.random.random((3,1))
z = np.random.random((1,4))

In [32]:
# y 값을 x의 각 열에 더합니다.
x+y

array([[1.19299099, 0.80985538, 1.16096567, 1.08321093],
       [1.24669294, 1.02958405, 0.68349205, 1.31940665],
       [1.54125034, 1.77461024, 1.15092568, 1.70623646]])

In [ ]:
# z의 각 원소를 대응되는 x의 행에 곱합니다.
x*z

- 비슷한 예제로 한 번 더 학습해봅시다.

In [ ]:
# 서로 다른 형태의 배열을 정의하여 a,b,c 각각 변수에 저장합니다.
a = np.random.random((3,4))
b = np.random.random((3,1))
c = np.random.random((3,))
print(a)
print(b)
print(c)

In [ ]:
# 각각의 연산이 어떤 결과를 보여주는지 확인한다.
print(b + b.T)

In [ ]:
print(a + b)

In [ ]:
print(a + c)

In [ ]:
print(b + c)

## 3. Practical Python Tips
- 본 노트북에서는 복잡한 코드를 동일한 기능을 하면서 가독성을 높이고 간결한 코드로 바꿔보고자 합시다.

In [ ]:
# 기존 코드
squares = []
for i in range(10):
    squares.append(i**2)

print(squares)

In [ ]:
# 간결화된 코드
squares = [i**2 for i in range(10)]
print(squares)

- 조건문을 포함한 형태로 간결화할 수 있습니다.

In [ ]:
# i가 홀수일 경우에만 odds에 i**2 값을 추가한다.
odds = [i**2 for i in range(10) if i%2 == 1]
print(odds)

- 한 번에 여러 개의 값을 여러 개의 변수에 저장할 수 있습니다. 

In [ ]:
age, name, pets = 20, 'Joy', ['cat']
x, y, z = ('Tensorflow', 'PyTorch', 'Chainer')

- 함수에서 여러 개의 값을 한 번에 리턴(return)할 수 있습니다.

In [ ]:
def some_func(): 
    return 10, 1
ten, one = some_func()

- 구분 기호를 이용하여 리스트 원소들을 string으로 출력할 수 있습니다.

In [ ]:
",".join(['1', '2', '3']) == '1,2,3'

- 하나의 string에는 작은 따옴표와 큰 따옴표가 혼용되어 있을 수 있습니다.

In [ ]:
message = 'I like "single" quotes.'
reply = "I prefer 'double' quotes"

In [ ]:
print(message)
print(reply)